ALTER TABLE profiles 
ADD COLUMN pet_type TEXT DEFAULT NULL,
ADD COLUMN pet_name TEXT DEFAULT NULL,
ADD COLUMN pet_level INT DEFAULT 1,
ADD COLUMN pet_health INT DEFAULT 100,
ADD COLUMN pet_last_fed_at TIMESTAMPTZ DEFAULT NOW();
