'use client';

import React, { useState, useEffect } from 'react';
import QuestionCard from '@/components/QuestionCard';
import { Filter, SlidersHorizontal, BookOpen, Layers, Target, ChevronDown, Info } from 'lucide-react';

export default function FeedPage() {
    const [questions, setQuestions] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);

    // Filters
    const [selectedSubject, setSelectedSubject] = useState('');
    const [selectedClass, setSelectedClass] = useState('');
    const [selectedDifficulty, setSelectedDifficulty] = useState('');

    useEffect(() => {
        let mounted = true;
        setLoading(true);
        let url = '/api/questions?limit=150';

        // Add simple query params if you implemented filtering in API,
        // otherwise we filter on client. Assuming client filter for this example to handle the 500 injections smoothly

        fetch(url)
            .then(res => res.json())
            .then(data => {
                if (!mounted) return;
                setQuestions(Array.isArray(data) ? data : data.questions || []);
            })
            .catch(console.error)
            .finally(() => mounted && setLoading(false));

        return () => { mounted = false; };
    }, []);

    // Filter logic
    const filteredQuestions = questions.filter((q: any) => {
        if (selectedSubject && q.subject !== selectedSubject) return false;

        if (selectedClass) {
            // Handle "All" class mapping, or actual number matching
            if (q.classGrade !== selectedClass && q.class_grade !== selectedClass && q.classGrade !== 'All' && q.class_grade !== 'All') {
                return false;
            }
        }

        if (selectedDifficulty && q.difficulty && q.difficulty.toLowerCase() !== selectedDifficulty.toLowerCase()) return false;
        return true;
    });

    return (
        <div className="min-h-[100dvh] bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100 pb-24 pt-4 sm:pt-8 md:pt-12 relative overflow-hidden">
            {/* Decorative Blur Backgrounds */}
            <div className="absolute top-0 left-1/4 w-96 h-96 bg-blue-400/10 dark:bg-blue-600/10 rounded-full mix-blend-overlay filter blur-3xl" />
            <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-indigo-400/10 dark:bg-indigo-600/10 rounded-full mix-blend-overlay filter blur-3xl" />

            <main className="max-w-4xl mx-auto px-4 sm:px-6 relative z-10 w-full">
                {/* Header */}
                <div className="mb-8 md:mb-10 hidden md:flex flex-col md:flex-row md:items-end justify-between gap-6">
                    <div>
                        <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-indigo-100/50 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300 text-xs font-bold mb-3 border border-indigo-200/50 dark:border-indigo-800/50">
                            <span className="relative flex h-2 w-2">
                                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-indigo-400 dark:bg-indigo-500 opacity-75"></span>
                                <span className="relative inline-flex rounded-full h-2 w-2 bg-indigo-500 dark:bg-indigo-400"></span>
                            </span>
                            Live Feed
                        </div>
                        <h1 className="text-3xl md:text-5xl font-black tracking-tight text-slate-900 dark:text-white mb-2">
                            Explore Questions
                        </h1>
                        <p className="text-slate-500 dark:text-slate-400 font-medium max-w-lg mx-auto md:mx-0">
                            Find challenges, practice topics, and test your knowledge against the best questions generated by top teachers.
                        </p>
                    </div>
                </div>

                {/* Modern Filter Selectors */}
                <div className="bg-white/70 dark:bg-slate-900/70 backdrop-blur-xl border border-slate-200/60 dark:border-slate-800/60 p-5 rounded-[2rem] shadow-sm mb-8">
                    <div className="flex items-center gap-2 mb-4 px-2">
                        <SlidersHorizontal className="w-5 h-5 text-indigo-500 dark:text-indigo-400" />
                        <h3 className="font-bold text-slate-800 dark:text-slate-200 text-sm tracking-wide">FILTER FEED</h3>
                    </div>

                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                        {/* Subject Selector */}
                        <div className="relative group">
                            <div className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400 dark:text-slate-500 pointer-events-none group-focus-within:text-blue-500 dark:group-focus-within:text-blue-400 transition-colors">
                                <BookOpen className="w-4 h-4" />
                            </div>
                            <select
                                value={selectedSubject}
                                onChange={(e) => setSelectedSubject(e.target.value)}
                                className="w-full appearance-none bg-slate-50/50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 hover:border-blue-300 dark:hover:border-blue-700 focus:border-blue-500 dark:focus:border-blue-500 focus:ring-2 focus:ring-blue-100 dark:focus:ring-blue-900/50 rounded-2xl pl-10 pr-10 py-3.5 text-sm font-bold text-slate-700 dark:text-slate-200 outline-none transition-all cursor-pointer shadow-sm"
                            >
                                <option value="">All Subjects</option>
                                <option value="Mathematics">Mathematics</option>
                                <option value="Science">Science</option>
                                <option value="English">English</option>
                                <option value="SST">Social Studies</option>
                            </select>
                            <div className="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none">
                                <ChevronDown className="w-4 h-4 text-slate-400 dark:text-slate-500" />
                            </div>
                        </div>

                        {/* Class Selector */}
                        <div className="relative group">
                            <div className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400 dark:text-slate-500 pointer-events-none group-focus-within:text-fuchsia-500 dark:group-focus-within:text-fuchsia-400 transition-colors">
                                <Layers className="w-4 h-4" />
                            </div>
                            <select
                                value={selectedClass}
                                onChange={(e) => setSelectedClass(e.target.value)}
                                className="w-full appearance-none bg-slate-50/50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 hover:border-fuchsia-300 dark:hover:border-fuchsia-700 focus:border-fuchsia-500 dark:focus:border-fuchsia-500 focus:ring-2 focus:ring-fuchsia-100 dark:focus:ring-fuchsia-900/50 rounded-2xl pl-10 pr-10 py-3.5 text-sm font-bold text-slate-700 dark:text-slate-200 outline-none transition-all cursor-pointer shadow-sm disabled:opacity-50"
                                disabled={selectedSubject === 'English'}
                            >
                                <option value="">All Classes</option>
                                <option value="6">Class 6</option>
                                <option value="7">Class 7</option>
                                <option value="8">Class 8</option>
                                <option value="9">Class 9</option>
                                <option value="10">Class 10</option>
                                <option value="11">Class 11</option>
                                <option value="12">Class 12</option>
                            </select>
                            <div className="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none">
                                <ChevronDown className="w-4 h-4 text-slate-400 dark:text-slate-500" />
                            </div>
                        </div>

                        {/* Difficulty Selector */}
                        <div className="relative group">
                            <div className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400 dark:text-slate-500 pointer-events-none group-focus-within:text-orange-500 dark:group-focus-within:text-orange-400 transition-colors">
                                <Target className="w-4 h-4" />
                            </div>
                            <select
                                value={selectedDifficulty}
                                onChange={(e) => setSelectedDifficulty(e.target.value)}
                                className="w-full appearance-none bg-slate-50/50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 hover:border-orange-300 dark:hover:border-orange-700 focus:border-orange-500 dark:focus:border-orange-500 focus:ring-2 focus:ring-orange-100 dark:focus:ring-orange-900/50 rounded-2xl pl-10 pr-10 py-3.5 text-sm font-bold text-slate-700 dark:text-slate-200 outline-none transition-all cursor-pointer shadow-sm"
                            >
                                <option value="">Any Difficulty</option>
                                <option value="easy">Easy</option>
                                <option value="moderate">Moderate</option>
                                <option value="hard">Hard</option>
                            </select>
                            <div className="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none">
                                <ChevronDown className="w-4 h-4 text-slate-400 dark:text-slate-500" />
                            </div>
                        </div>
                    </div>

                    {selectedSubject === 'English' && (
                        <p className="mt-3 text-xs font-semibold text-fuchsia-600 dark:text-fuchsia-400 px-2 flex items-center gap-1.5 animate-in fade-in slide-in-from-top-1">
                            <Info className="w-3.5 h-3.5" />
                            English language questions are applicable to all class grades.
                        </p>
                    )}
                </div>

                {/* Feed Content */}
                {loading ? (
                    <div className="flex flex-col items-center justify-center py-20 space-y-4">
                        <div className="w-10 h-10 border-4 border-slate-200 dark:border-slate-800 border-t-indigo-600 dark:border-t-indigo-500 rounded-full animate-spin"></div>
                        <p className="font-bold text-slate-500 dark:text-slate-400">Loading feed...</p>
                    </div>
                ) : filteredQuestions.length === 0 ? (
                    <div className="bg-white dark:bg-slate-900 rounded-3xl p-12 text-center border border-slate-100 dark:border-slate-800 shadow-sm flex flex-col items-center">
                        <div className="w-16 h-16 bg-slate-50 dark:bg-slate-800/50 rounded-2xl flex items-center justify-center mb-4">
                            <Filter className="w-8 h-8 text-slate-300 dark:text-slate-600" />
                        </div>
                        <h3 className="text-xl font-bold text-slate-800 dark:text-slate-200 mb-2">No matching questions</h3>
                        <p className="text-slate-500 dark:text-slate-400 font-medium max-w-sm">
                            We couldn't find any questions matching your current filters. Try changing the selectors above or clear the filters to see all.
                        </p>
                        {(selectedSubject || selectedClass || selectedDifficulty) && (
                            <button
                                onClick={() => { setSelectedSubject(''); setSelectedClass(''); setSelectedDifficulty(''); }}
                                className="mt-6 px-6 py-2.5 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 font-bold rounded-xl transition-colors"
                            >
                                Clear all filters
                            </button>
                        )}
                    </div>
                ) : (
                    <div className="space-y-6">
                        <div className="text-sm font-bold text-slate-500 dark:text-slate-400 px-2 pb-2 mb-2 border-b border-slate-200/60 dark:border-slate-800/60 inline-flex items-center gap-2">
                            Showing {filteredQuestions.length} Questions
                        </div>
                        {filteredQuestions.map((q: any) => (
                            <QuestionCard key={q.id} q={q} />
                        ))}
                    </div>
                )}
            </main>
        </div>
    );
}


